import type {
  ComputeResource,
  Container,
  Template,
  Heartbeat,
  Miner,
  SshKey,
} from "@/lib/db/schema";
import type { PlatformStats, AdminUserInfo, ResourceWithDetails } from "./types";

// ─── Helpers ──────────────────────────────────────────────────

function daysAgo(days: number): Date {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000);
}

function hoursAgo(hours: number): Date {
  return new Date(Date.now() - hours * 60 * 60 * 1000);
}

function hoursFromNow(hours: number): Date {
  return new Date(Date.now() + hours * 60 * 60 * 1000);
}

// ─── Miners ───────────────────────────────────────────────────

export const mockMiners: Miner[] = [
  {
    id: "miner-001",
    userId: "user-provider-001",
    name: "Lagos GPU Farm",
    location: "Lagos, Nigeria",
    description: "Enterprise-grade GPU cluster in Lagos data center",
    status: "active",
    hotkey: "5HYk...abc1",
    coldkey: "5CqW...xyz1",
    minerUid: "uid-101",
    subnetUid: "sn-42",
    totalEarnings: 15420.50,
    createdAt: daysAgo(120),
  },
  {
    id: "miner-002",
    userId: "user-provider-002",
    name: "Nairobi Compute Hub",
    location: "Nairobi, Kenya",
    description: "Mixed CPU/GPU compute in Nairobi tech park",
    status: "active",
    hotkey: "5HYk...abc2",
    coldkey: "5CqW...xyz2",
    minerUid: "uid-102",
    subnetUid: "sn-42",
    totalEarnings: 8730.25,
    createdAt: daysAgo(95),
  },
  {
    id: "miner-003",
    userId: "user-provider-003",
    name: "Cape Town Server Room",
    location: "Cape Town, South Africa",
    description: "High-performance GPU nodes at Cape Town IX",
    status: "active",
    hotkey: "5HYk...abc3",
    coldkey: "5CqW...xyz3",
    minerUid: "uid-103",
    subnetUid: "sn-42",
    totalEarnings: 22100.00,
    createdAt: daysAgo(200),
  },
  {
    id: "miner-004",
    userId: "user-provider-004",
    name: "Accra Node Alpha",
    location: "Accra, Ghana",
    description: "Budget-friendly CPU instances in Accra",
    status: "active",
    hotkey: "5HYk...abc4",
    coldkey: "5CqW...xyz4",
    minerUid: "uid-104",
    subnetUid: "sn-42",
    totalEarnings: 3200.75,
    createdAt: daysAgo(60),
  },
  {
    id: "miner-005",
    userId: "user-provider-005",
    name: "Amsterdam EU Gateway",
    location: "Amsterdam, Netherlands",
    description: "Low-latency GPU cluster for European clients",
    status: "active",
    hotkey: "5HYk...abc5",
    coldkey: "5CqW...xyz5",
    minerUid: "uid-105",
    subnetUid: "sn-42",
    totalEarnings: 31500.00,
    createdAt: daysAgo(180),
  },
  {
    id: "miner-006",
    userId: "user-provider-006",
    name: "London Bridge DC",
    location: "London, United Kingdom",
    description: "Premium H100 nodes in London Docklands",
    status: "active",
    hotkey: "5HYk...abc6",
    coldkey: "5CqW...xyz6",
    minerUid: "uid-106",
    subnetUid: "sn-42",
    totalEarnings: 45800.00,
    createdAt: daysAgo(250),
  },
  {
    id: "miner-007",
    userId: "user-provider-007",
    name: "Lagos Lite Nodes",
    location: "Lagos, Nigeria",
    description: "Affordable CPU-only compute for dev/test workloads",
    status: "inactive",
    hotkey: "5HYk...abc7",
    coldkey: "5CqW...xyz7",
    minerUid: "uid-107",
    subnetUid: "sn-42",
    totalEarnings: 1240.00,
    createdAt: daysAgo(45),
  },
  {
    id: "miner-008",
    userId: "user-provider-008",
    name: "Nairobi ML Cluster",
    location: "Nairobi, Kenya",
    description: "Dedicated ML training cluster with A100s",
    status: "active",
    hotkey: "5HYk...abc8",
    coldkey: "5CqW...xyz8",
    minerUid: "uid-108",
    subnetUid: "sn-42",
    totalEarnings: 18900.50,
    createdAt: daysAgo(140),
  },
  {
    id: "miner-009",
    userId: "user-provider-009",
    name: "Cape Town Edge",
    location: "Cape Town, South Africa",
    description: "Edge compute nodes for inference workloads",
    status: "active",
    hotkey: "5HYk...abc9",
    coldkey: "5CqW...xyz9",
    minerUid: "uid-109",
    subnetUid: "sn-42",
    totalEarnings: 5600.25,
    createdAt: daysAgo(75),
  },
  {
    id: "miner-010",
    userId: "user-provider-010",
    name: "Accra Budget Compute",
    location: "Accra, Ghana",
    description: "Cost-effective compute for batch processing",
    status: "suspended",
    hotkey: "5HYk...abc0",
    coldkey: "5CqW...xyz0",
    minerUid: "uid-110",
    subnetUid: "sn-42",
    totalEarnings: 890.00,
    createdAt: daysAgo(30),
  },
];

// ─── Compute Resources ────────────────────────────────────────

export const mockResources: ComputeResource[] = [
  // GPU Resources
  {
    id: "res-gpu-001",
    minerId: "miner-001",
    resourceType: "gpu",
    validationStatus: "verified",
    verifierStatus: "verified",
    adminApprovalStatus: "verified",
    isBlacklisted: false,
    isActive: true,
    cpuModel: "AMD Ryzen 9 5900X",
    cpuCores: 12,
    cpuThreads: 24,
    cpuArchitecture: "x86_64",
    gpuModel: "NVIDIA RTX 3060",
    gpuCount: 1,
    gpuVramGb: 12,
    gpuCudaCores: 3584,
    gpuTensorCores: 112,
    ramGb: 32,
    storageGb: 512,
    storageType: "NVMe SSD",
    publicIp: "102.89.23.45",
    sshPort: 22,
    sshUsername: "polaris",
    rentalPort: 30001,
    cpuPowScore: 85.2,
    gpuPowScore: 72.5,
    dockerReady: true,
    connectionRtt: 45,
    hourlyPrice: 0.35,
    allowMining: true,
    rentalUserId: null,
    rentalStartDate: null,
    rentalEndDate: null,
    containerId: null,
    region: "Lagos",
    country: "NG",
    verificationNotes: "Verified via watchtower",
    adminNotes: null,
    createdAt: daysAgo(90),
    updatedAt: hoursAgo(1),
  },
  {
    id: "res-gpu-002",
    minerId: "miner-002",
    resourceType: "gpu",
    validationStatus: "verified",
    verifierStatus: "verified",
    adminApprovalStatus: "verified",
    isBlacklisted: false,
    isActive: true,
    cpuModel: "Intel Core i9-12900K",
    cpuCores: 16,
    cpuThreads: 24,
    cpuArchitecture: "x86_64",
    gpuModel: "NVIDIA RTX 3090",
    gpuCount: 1,
    gpuVramGb: 24,
    gpuCudaCores: 10496,
    gpuTensorCores: 328,
    ramGb: 64,
    storageGb: 1000,
    storageType: "NVMe SSD",
    publicIp: "196.201.214.78",
    sshPort: 22,
    sshUsername: "polaris",
    rentalPort: 30002,
    cpuPowScore: 92.1,
    gpuPowScore: 88.3,
    dockerReady: true,
    connectionRtt: 62,
    hourlyPrice: 0.85,
    allowMining: true,
    rentalUserId: null,
    rentalStartDate: null,
    rentalEndDate: null,
    containerId: null,
    region: "Nairobi",
    country: "KE",
    verificationNotes: "Verified via watchtower",
    adminNotes: null,
    createdAt: daysAgo(80),
    updatedAt: hoursAgo(2),
  },
  {
    id: "res-gpu-003",
    minerId: "miner-003",
    resourceType: "gpu",
    validationStatus: "verified",
    verifierStatus: "verified",
    adminApprovalStatus: "verified",
    isBlacklisted: false,
    isActive: true,
    cpuModel: "AMD EPYC 7543",
    cpuCores: 32,
    cpuThreads: 64,
    cpuArchitecture: "x86_64",
    gpuModel: "NVIDIA RTX 4090",
    gpuCount: 2,
    gpuVramGb: 24,
    gpuCudaCores: 16384,
    gpuTensorCores: 512,
    ramGb: 128,
    storageGb: 2000,
    storageType: "NVMe SSD",
    publicIp: "41.76.108.12",
    sshPort: 22,
    sshUsername: "polaris",
    rentalPort: 30003,
    cpuPowScore: 96.5,
    gpuPowScore: 95.2,
    dockerReady: true,
    connectionRtt: 38,
    hourlyPrice: 1.50,
    allowMining: false,
    rentalUserId: "user-001",
    rentalStartDate: hoursAgo(12),
    rentalEndDate: hoursFromNow(12),
    containerId: "ctr-001",
    region: "Cape Town",
    country: "ZA",
    verificationNotes: "Premium node, dual 4090",
    adminNotes: "Priority provider",
    createdAt: daysAgo(150),
    updatedAt: hoursAgo(0.5),
  },
  {
    id: "res-gpu-004",
    minerId: "miner-005",
    resourceType: "gpu",
    validationStatus: "verified",
    verifierStatus: "verified",
    adminApprovalStatus: "verified",
    isBlacklisted: false,
    isActive: true,
    cpuModel: "AMD EPYC 7763",
    cpuCores: 64,
    cpuThreads: 128,
    cpuArchitecture: "x86_64",
    gpuModel: "NVIDIA A100 40GB",
    gpuCount: 4,
    gpuVramGb: 40,
    gpuCudaCores: 6912,
    gpuTensorCores: 432,
    ramGb: 256,
    storageGb: 4000,
    storageType: "NVMe SSD",
    publicIp: "185.107.56.200",
    sshPort: 22,
    sshUsername: "polaris",
    rentalPort: 30004,
    cpuPowScore: 98.0,
    gpuPowScore: 96.8,
    dockerReady: true,
    connectionRtt: 15,
    hourlyPrice: 2.80,
    allowMining: false,
    rentalUserId: null,
    rentalStartDate: null,
    rentalEndDate: null,
    containerId: null,
    region: "Amsterdam",
    country: "NL",
    verificationNotes: "Enterprise A100 cluster",
    adminNotes: null,
    createdAt: daysAgo(130),
    updatedAt: hoursAgo(3),
  },
  {
    id: "res-gpu-005",
    minerId: "miner-006",
    resourceType: "gpu",
    validationStatus: "verified",
    verifierStatus: "verified",
    adminApprovalStatus: "verified",
    isBlacklisted: false,
    isActive: true,
    cpuModel: "AMD EPYC 9654",
    cpuCores: 96,
    cpuThreads: 192,
    cpuArchitecture: "x86_64",
    gpuModel: "NVIDIA A100 80GB",
    gpuCount: 8,
    gpuVramGb: 80,
    gpuCudaCores: 6912,
    gpuTensorCores: 432,
    ramGb: 512,
    storageGb: 8000,
    storageType: "NVMe SSD",
    publicIp: "51.132.45.88",
    sshPort: 22,
    sshUsername: "polaris",
    rentalPort: 30005,
    cpuPowScore: 99.2,
    gpuPowScore: 98.5,
    dockerReady: true,
    connectionRtt: 12,
    hourlyPrice: 3.50,
    allowMining: false,
    rentalUserId: null,
    rentalStartDate: null,
    rentalEndDate: null,
    containerId: null,
    region: "London",
    country: "GB",
    verificationNotes: "Premium A100 80GB x8 node",
    adminNotes: "Flagship provider",
    createdAt: daysAgo(200),
    updatedAt: hoursAgo(1),
  },
  {
    id: "res-gpu-006",
    minerId: "miner-008",
    resourceType: "gpu",
    validationStatus: "verified",
    verifierStatus: "verified",
    adminApprovalStatus: "verified",
    isBlacklisted: false,
    isActive: true,
    cpuModel: "Intel Xeon w9-3495X",
    cpuCores: 56,
    cpuThreads: 112,
    cpuArchitecture: "x86_64",
    gpuModel: "NVIDIA H100",
    gpuCount: 4,
    gpuVramGb: 80,
    gpuCudaCores: 16896,
    gpuTensorCores: 528,
    ramGb: 512,
    storageGb: 8000,
    storageType: "NVMe SSD",
    publicIp: "196.201.215.90",
    sshPort: 22,
    sshUsername: "polaris",
    rentalPort: 30006,
    cpuPowScore: 99.5,
    gpuPowScore: 99.8,
    dockerReady: true,
    connectionRtt: 55,
    hourlyPrice: 4.50,
    allowMining: false,
    rentalUserId: null,
    rentalStartDate: null,
    rentalEndDate: null,
    containerId: null,
    region: "Nairobi",
    country: "KE",
    verificationNotes: "H100 cluster, top-tier",
    adminNotes: "Reserved for enterprise clients",
    createdAt: daysAgo(100),
    updatedAt: hoursAgo(0.25),
  },
  // CPU Resources
  {
    id: "res-cpu-001",
    minerId: "miner-004",
    resourceType: "cpu",
    validationStatus: "verified",
    verifierStatus: "verified",
    adminApprovalStatus: "verified",
    isBlacklisted: false,
    isActive: true,
    cpuModel: "AMD Ryzen 7 5800X",
    cpuCores: 8,
    cpuThreads: 16,
    cpuArchitecture: "x86_64",
    gpuModel: null,
    gpuCount: null,
    gpuVramGb: null,
    gpuCudaCores: null,
    gpuTensorCores: null,
    ramGb: 32,
    storageGb: 500,
    storageType: "SSD",
    publicIp: "154.160.12.33",
    sshPort: 22,
    sshUsername: "polaris",
    rentalPort: 30101,
    cpuPowScore: 78.5,
    gpuPowScore: null,
    dockerReady: true,
    connectionRtt: 70,
    hourlyPrice: 0.15,
    allowMining: true,
    rentalUserId: null,
    rentalStartDate: null,
    rentalEndDate: null,
    containerId: null,
    region: "Accra",
    country: "GH",
    verificationNotes: "Budget CPU node",
    adminNotes: null,
    createdAt: daysAgo(50),
    updatedAt: hoursAgo(4),
  },
  {
    id: "res-cpu-002",
    minerId: "miner-001",
    resourceType: "cpu",
    validationStatus: "verified",
    verifierStatus: "verified",
    adminApprovalStatus: "verified",
    isBlacklisted: false,
    isActive: true,
    cpuModel: "Intel Xeon E-2388G",
    cpuCores: 8,
    cpuThreads: 16,
    cpuArchitecture: "x86_64",
    gpuModel: null,
    gpuCount: null,
    gpuVramGb: null,
    gpuCudaCores: null,
    gpuTensorCores: null,
    ramGb: 64,
    storageGb: 1000,
    storageType: "NVMe SSD",
    publicIp: "102.89.23.46",
    sshPort: 22,
    sshUsername: "polaris",
    rentalPort: 30102,
    cpuPowScore: 82.3,
    gpuPowScore: null,
    dockerReady: true,
    connectionRtt: 42,
    hourlyPrice: 0.25,
    allowMining: true,
    rentalUserId: "user-002",
    rentalStartDate: hoursAgo(6),
    rentalEndDate: hoursFromNow(18),
    containerId: "ctr-002",
    region: "Lagos",
    country: "NG",
    verificationNotes: "Xeon workstation",
    adminNotes: null,
    createdAt: daysAgo(85),
    updatedAt: hoursAgo(2),
  },
  {
    id: "res-cpu-003",
    minerId: "miner-003",
    resourceType: "cpu",
    validationStatus: "verified",
    verifierStatus: "verified",
    adminApprovalStatus: "verified",
    isBlacklisted: false,
    isActive: true,
    cpuModel: "AMD EPYC 7543",
    cpuCores: 32,
    cpuThreads: 64,
    cpuArchitecture: "x86_64",
    gpuModel: null,
    gpuCount: null,
    gpuVramGb: null,
    gpuCudaCores: null,
    gpuTensorCores: null,
    ramGb: 128,
    storageGb: 2000,
    storageType: "NVMe SSD",
    publicIp: "41.76.108.13",
    sshPort: 22,
    sshUsername: "polaris",
    rentalPort: 30103,
    cpuPowScore: 94.7,
    gpuPowScore: null,
    dockerReady: true,
    connectionRtt: 35,
    hourlyPrice: 0.45,
    allowMining: true,
    rentalUserId: null,
    rentalStartDate: null,
    rentalEndDate: null,
    containerId: null,
    region: "Cape Town",
    country: "ZA",
    verificationNotes: "High-core CPU node",
    adminNotes: null,
    createdAt: daysAgo(140),
    updatedAt: hoursAgo(5),
  },
  {
    id: "res-cpu-004",
    minerId: "miner-005",
    resourceType: "cpu",
    validationStatus: "verified",
    verifierStatus: "verified",
    adminApprovalStatus: "verified",
    isBlacklisted: false,
    isActive: true,
    cpuModel: "AMD EPYC 7763",
    cpuCores: 64,
    cpuThreads: 128,
    cpuArchitecture: "x86_64",
    gpuModel: null,
    gpuCount: null,
    gpuVramGb: null,
    gpuCudaCores: null,
    gpuTensorCores: null,
    ramGb: 256,
    storageGb: 4000,
    storageType: "NVMe SSD",
    publicIp: "185.107.56.201",
    sshPort: 22,
    sshUsername: "polaris",
    rentalPort: 30104,
    cpuPowScore: 97.8,
    gpuPowScore: null,
    dockerReady: true,
    connectionRtt: 18,
    hourlyPrice: 0.65,
    allowMining: false,
    rentalUserId: null,
    rentalStartDate: null,
    rentalEndDate: null,
    containerId: null,
    region: "Amsterdam",
    country: "NL",
    verificationNotes: "Enterprise CPU node",
    adminNotes: null,
    createdAt: daysAgo(125),
    updatedAt: hoursAgo(1),
  },
  {
    id: "res-cpu-005",
    minerId: "miner-009",
    resourceType: "cpu",
    validationStatus: "pending",
    verifierStatus: "pending",
    adminApprovalStatus: "pending",
    isBlacklisted: false,
    isActive: false,
    cpuModel: "Intel Core i7-13700K",
    cpuCores: 16,
    cpuThreads: 24,
    cpuArchitecture: "x86_64",
    gpuModel: null,
    gpuCount: null,
    gpuVramGb: null,
    gpuCudaCores: null,
    gpuTensorCores: null,
    ramGb: 32,
    storageGb: 500,
    storageType: "SSD",
    publicIp: "41.76.109.55",
    sshPort: 22,
    sshUsername: "polaris",
    rentalPort: 30105,
    cpuPowScore: 80.1,
    gpuPowScore: null,
    dockerReady: true,
    connectionRtt: 40,
    hourlyPrice: 0.20,
    allowMining: true,
    rentalUserId: null,
    rentalStartDate: null,
    rentalEndDate: null,
    containerId: null,
    region: "Cape Town",
    country: "ZA",
    verificationNotes: null,
    adminNotes: "Awaiting verification",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: "res-cpu-006",
    minerId: "miner-007",
    resourceType: "cpu",
    validationStatus: "verified",
    verifierStatus: "verified",
    adminApprovalStatus: "rejected",
    isBlacklisted: false,
    isActive: false,
    cpuModel: "AMD Ryzen 5 5600X",
    cpuCores: 6,
    cpuThreads: 12,
    cpuArchitecture: "x86_64",
    gpuModel: null,
    gpuCount: null,
    gpuVramGb: null,
    gpuCudaCores: null,
    gpuTensorCores: null,
    ramGb: 16,
    storageGb: 256,
    storageType: "SSD",
    publicIp: "102.89.24.10",
    sshPort: 22,
    sshUsername: "polaris",
    rentalPort: 30106,
    cpuPowScore: 65.3,
    gpuPowScore: null,
    dockerReady: false,
    connectionRtt: 85,
    hourlyPrice: 0.10,
    allowMining: true,
    rentalUserId: null,
    rentalStartDate: null,
    rentalEndDate: null,
    containerId: null,
    region: "Lagos",
    country: "NG",
    verificationNotes: "Low specs, Docker not ready",
    adminNotes: "Rejected: does not meet minimum requirements",
    createdAt: daysAgo(40),
    updatedAt: daysAgo(38),
  },
];

// ─── Templates ────────────────────────────────────────────────

export const mockTemplates: Template[] = [
  {
    id: "tpl-001",
    name: "PyTorch",
    description: "PyTorch 2.3 with CUDA 12.4 — pre-configured for deep learning training and inference",
    category: "ml-framework",
    image: "pytorch/pytorch:2.3.0-cuda12.4-cudnn9-runtime",
    logoUrl: "/logos/pytorch.svg",
    ports: JSON.stringify([8888, 6006]),
    services: JSON.stringify({ jupyter: 8888, tensorboard: 6006 }),
    gpuRequired: true,
    minGpuMemory: "8GB",
    deploymentType: "docker_based",
    scriptPath: null,
    scriptConfig: null,
    isActive: true,
    createdAt: daysAgo(180),
  },
  {
    id: "tpl-002",
    name: "TensorFlow",
    description: "TensorFlow 2.16 with CUDA — includes Keras 3.0 and TensorBoard",
    category: "ml-framework",
    image: "tensorflow/tensorflow:2.16.1-gpu-jupyter",
    logoUrl: "/logos/tensorflow.svg",
    ports: JSON.stringify([8888, 6006]),
    services: JSON.stringify({ jupyter: 8888, tensorboard: 6006 }),
    gpuRequired: true,
    minGpuMemory: "8GB",
    deploymentType: "docker_based",
    scriptPath: null,
    scriptConfig: null,
    isActive: true,
    createdAt: daysAgo(180),
  },
  {
    id: "tpl-003",
    name: "Ubuntu Desktop",
    description: "Ubuntu 22.04 LTS with SSH — clean environment for general-purpose workloads",
    category: "os",
    image: "ubuntu:22.04",
    logoUrl: "/logos/ubuntu.svg",
    ports: JSON.stringify([22]),
    services: JSON.stringify({ ssh: 22 }),
    gpuRequired: false,
    minGpuMemory: null,
    deploymentType: "docker_based",
    scriptPath: null,
    scriptConfig: null,
    isActive: true,
    createdAt: daysAgo(180),
  },
  {
    id: "tpl-004",
    name: "Jupyter Lab",
    description: "JupyterLab with Python 3.11, scientific stack (NumPy, Pandas, Matplotlib)",
    category: "notebook",
    image: "jupyter/scipy-notebook:latest",
    logoUrl: "/logos/jupyter.svg",
    ports: JSON.stringify([8888]),
    services: JSON.stringify({ jupyter: 8888 }),
    gpuRequired: false,
    minGpuMemory: null,
    deploymentType: "docker_based",
    scriptPath: null,
    scriptConfig: null,
    isActive: true,
    createdAt: daysAgo(180),
  },
  {
    id: "tpl-005",
    name: "VS Code Server",
    description: "Code-server (VS Code in browser) with Python, Node.js, and common extensions",
    category: "ide",
    image: "codercom/code-server:latest",
    logoUrl: "/logos/vscode.svg",
    ports: JSON.stringify([8080, 22]),
    services: JSON.stringify({ vscode: 8080, ssh: 22 }),
    gpuRequired: false,
    minGpuMemory: null,
    deploymentType: "docker_based",
    scriptPath: null,
    scriptConfig: null,
    isActive: true,
    createdAt: daysAgo(160),
  },
  {
    id: "tpl-006",
    name: "ComfyUI",
    description: "ComfyUI node-based Stable Diffusion interface with popular models pre-loaded",
    category: "ai-tool",
    image: "ghcr.io/ai-dock/comfyui:latest",
    logoUrl: "/logos/comfyui.svg",
    ports: JSON.stringify([8188, 22]),
    services: JSON.stringify({ comfyui: 8188, ssh: 22 }),
    gpuRequired: true,
    minGpuMemory: "12GB",
    deploymentType: "docker_based",
    scriptPath: null,
    scriptConfig: null,
    isActive: true,
    createdAt: daysAgo(120),
  },
  {
    id: "tpl-007",
    name: "Stable Diffusion WebUI",
    description: "AUTOMATIC1111 Stable Diffusion WebUI with SDXL support and common extensions",
    category: "ai-tool",
    image: "ghcr.io/ai-dock/stable-diffusion-webui:latest",
    logoUrl: "/logos/sd.svg",
    ports: JSON.stringify([7860, 22]),
    services: JSON.stringify({ webui: 7860, ssh: 22 }),
    gpuRequired: true,
    minGpuMemory: "12GB",
    deploymentType: "docker_based",
    scriptPath: null,
    scriptConfig: null,
    isActive: true,
    createdAt: daysAgo(120),
  },
  {
    id: "tpl-008",
    name: "CUDA Development",
    description: "NVIDIA CUDA 12.4 toolkit with cuDNN, NCCL, and development headers",
    category: "development",
    image: "nvidia/cuda:12.4.1-devel-ubuntu22.04",
    logoUrl: "/logos/cuda.svg",
    ports: JSON.stringify([22]),
    services: JSON.stringify({ ssh: 22 }),
    gpuRequired: true,
    minGpuMemory: "8GB",
    deploymentType: "docker_based",
    scriptPath: null,
    scriptConfig: null,
    isActive: true,
    createdAt: daysAgo(150),
  },
];

// ─── Heartbeats ───────────────────────────────────────────────

export const mockHeartbeats: Heartbeat[] = [
  {
    id: "hb-001",
    resourceId: "res-gpu-001",
    isOnline: true,
    health: "healthy",
    hasInternet: true,
    uptimeHours: 720.5,
    cpuUsagePercent: 15.3,
    memoryUsagePercent: 42.1,
    gpuUsagePercent: 5.0,
    gpuTempCelsius: 38,
    externalIp: "102.89.23.45",
    watchtowerDeployed: true,
    lastUpdatedAt: hoursAgo(0.1),
    createdAt: daysAgo(90),
  },
  {
    id: "hb-002",
    resourceId: "res-gpu-002",
    isOnline: true,
    health: "healthy",
    hasInternet: true,
    uptimeHours: 512.3,
    cpuUsagePercent: 22.7,
    memoryUsagePercent: 55.4,
    gpuUsagePercent: 12.0,
    gpuTempCelsius: 42,
    externalIp: "196.201.214.78",
    watchtowerDeployed: true,
    lastUpdatedAt: hoursAgo(0.05),
    createdAt: daysAgo(80),
  },
  {
    id: "hb-003",
    resourceId: "res-gpu-003",
    isOnline: true,
    health: "healthy",
    hasInternet: true,
    uptimeHours: 1440.0,
    cpuUsagePercent: 65.2,
    memoryUsagePercent: 78.9,
    gpuUsagePercent: 92.5,
    gpuTempCelsius: 72,
    externalIp: "41.76.108.12",
    watchtowerDeployed: true,
    lastUpdatedAt: hoursAgo(0.02),
    createdAt: daysAgo(150),
  },
  {
    id: "hb-004",
    resourceId: "res-gpu-004",
    isOnline: true,
    health: "healthy",
    hasInternet: true,
    uptimeHours: 2160.0,
    cpuUsagePercent: 8.1,
    memoryUsagePercent: 22.3,
    gpuUsagePercent: 0.0,
    gpuTempCelsius: 34,
    externalIp: "185.107.56.200",
    watchtowerDeployed: true,
    lastUpdatedAt: hoursAgo(0.15),
    createdAt: daysAgo(130),
  },
  {
    id: "hb-005",
    resourceId: "res-gpu-005",
    isOnline: true,
    health: "healthy",
    hasInternet: true,
    uptimeHours: 4320.0,
    cpuUsagePercent: 12.5,
    memoryUsagePercent: 18.7,
    gpuUsagePercent: 0.0,
    gpuTempCelsius: 31,
    externalIp: "51.132.45.88",
    watchtowerDeployed: true,
    lastUpdatedAt: hoursAgo(0.08),
    createdAt: daysAgo(200),
  },
  {
    id: "hb-006",
    resourceId: "res-gpu-006",
    isOnline: true,
    health: "warning",
    hasInternet: true,
    uptimeHours: 960.5,
    cpuUsagePercent: 45.8,
    memoryUsagePercent: 61.2,
    gpuUsagePercent: 35.0,
    gpuTempCelsius: 58,
    externalIp: "196.201.215.90",
    watchtowerDeployed: true,
    lastUpdatedAt: hoursAgo(0.03),
    createdAt: daysAgo(100),
  },
  {
    id: "hb-007",
    resourceId: "res-cpu-001",
    isOnline: true,
    health: "healthy",
    hasInternet: true,
    uptimeHours: 360.0,
    cpuUsagePercent: 10.2,
    memoryUsagePercent: 25.5,
    gpuUsagePercent: null,
    gpuTempCelsius: null,
    externalIp: "154.160.12.33",
    watchtowerDeployed: true,
    lastUpdatedAt: hoursAgo(0.2),
    createdAt: daysAgo(50),
  },
  {
    id: "hb-008",
    resourceId: "res-cpu-002",
    isOnline: true,
    health: "healthy",
    hasInternet: true,
    uptimeHours: 480.0,
    cpuUsagePercent: 55.3,
    memoryUsagePercent: 67.8,
    gpuUsagePercent: null,
    gpuTempCelsius: null,
    externalIp: "102.89.23.46",
    watchtowerDeployed: true,
    lastUpdatedAt: hoursAgo(0.1),
    createdAt: daysAgo(85),
  },
  {
    id: "hb-009",
    resourceId: "res-cpu-003",
    isOnline: true,
    health: "healthy",
    hasInternet: true,
    uptimeHours: 1080.0,
    cpuUsagePercent: 5.1,
    memoryUsagePercent: 12.3,
    gpuUsagePercent: null,
    gpuTempCelsius: null,
    externalIp: "41.76.108.13",
    watchtowerDeployed: true,
    lastUpdatedAt: hoursAgo(0.25),
    createdAt: daysAgo(140),
  },
  {
    id: "hb-010",
    resourceId: "res-cpu-004",
    isOnline: true,
    health: "healthy",
    hasInternet: true,
    uptimeHours: 2880.0,
    cpuUsagePercent: 3.2,
    memoryUsagePercent: 8.5,
    gpuUsagePercent: null,
    gpuTempCelsius: null,
    externalIp: "185.107.56.201",
    watchtowerDeployed: true,
    lastUpdatedAt: hoursAgo(0.12),
    createdAt: daysAgo(125),
  },
];

// ─── Containers ───────────────────────────────────────────────

export const mockContainers: Container[] = [
  {
    id: "ctr-001",
    userId: "mock-user-id",
    minerId: "miner-003",
    resourceId: "res-gpu-003",
    subscriptionId: null,
    templateId: "tpl-001",
    status: "running",
    paymentStatus: "paid",
    host: "41.76.108.12",
    port: 30003,
    sshUsername: "polaris",
    sshPassword: null,
    sshKeyFingerprint: "SHA256:abc123def456",
    authMethod: "key",
    image: "pytorch/pytorch:2.3.0-cuda12.4-cudnn9-runtime",
    containerName: "pytorch-training-4090",
    jupyterUrl: "http://41.76.108.12:8888",
    jupyterToken: "tok_abc123",
    accessUrls: JSON.stringify({ jupyter: "http://41.76.108.12:8888", tensorboard: "http://41.76.108.12:6006" }),
    duration: JSON.stringify({ hours: 24, minutes: 0 }),
    errorMessage: null,
    startedAt: hoursAgo(12),
    stoppedAt: null,
    expiresAt: hoursFromNow(12),
    scheduledTermination: hoursFromNow(12),
    createdAt: hoursAgo(12),
  },
  {
    id: "ctr-002",
    userId: "mock-user-id",
    minerId: "miner-001",
    resourceId: "res-cpu-002",
    subscriptionId: null,
    templateId: "tpl-003",
    status: "running",
    paymentStatus: "paid",
    host: "102.89.23.46",
    port: 30102,
    sshUsername: "polaris",
    sshPassword: "tmp_pw_xk29f",
    sshKeyFingerprint: null,
    authMethod: "password",
    image: "ubuntu:22.04",
    containerName: "ubuntu-dev-env",
    jupyterUrl: null,
    jupyterToken: null,
    accessUrls: JSON.stringify({ ssh: "102.89.23.46:30102" }),
    duration: JSON.stringify({ hours: 24, minutes: 0 }),
    errorMessage: null,
    startedAt: hoursAgo(6),
    stoppedAt: null,
    expiresAt: hoursFromNow(18),
    scheduledTermination: hoursFromNow(18),
    createdAt: hoursAgo(6),
  },
  {
    id: "ctr-003",
    userId: "mock-user-id",
    minerId: "miner-005",
    resourceId: "res-gpu-004",
    subscriptionId: null,
    templateId: "tpl-002",
    status: "stopped",
    paymentStatus: "paid",
    host: "185.107.56.200",
    port: 30004,
    sshUsername: "polaris",
    sshPassword: null,
    sshKeyFingerprint: "SHA256:def789ghi012",
    authMethod: "key",
    image: "tensorflow/tensorflow:2.16.1-gpu-jupyter",
    containerName: "tensorflow-a100",
    jupyterUrl: null,
    jupyterToken: null,
    accessUrls: null,
    duration: JSON.stringify({ hours: 8, minutes: 0 }),
    errorMessage: null,
    startedAt: daysAgo(2),
    stoppedAt: hoursAgo(40),
    expiresAt: hoursAgo(40),
    scheduledTermination: null,
    createdAt: daysAgo(2),
  },
  {
    id: "ctr-004",
    userId: "mock-user-id",
    minerId: "miner-006",
    resourceId: "res-gpu-005",
    subscriptionId: null,
    templateId: "tpl-006",
    status: "terminated",
    paymentStatus: "paid",
    host: "51.132.45.88",
    port: 30005,
    sshUsername: "polaris",
    sshPassword: null,
    sshKeyFingerprint: "SHA256:jkl345mno678",
    authMethod: "key",
    image: "ghcr.io/ai-dock/comfyui:latest",
    containerName: "comfyui-a100",
    jupyterUrl: null,
    jupyterToken: null,
    accessUrls: null,
    duration: JSON.stringify({ hours: 4, minutes: 0 }),
    errorMessage: null,
    startedAt: daysAgo(5),
    stoppedAt: daysAgo(5),
    expiresAt: daysAgo(5),
    scheduledTermination: null,
    createdAt: daysAgo(5),
  },
  {
    id: "ctr-005",
    userId: "mock-user-id",
    minerId: "miner-002",
    resourceId: "res-gpu-002",
    subscriptionId: null,
    templateId: "tpl-005",
    status: "failed",
    paymentStatus: "refunded",
    host: null,
    port: null,
    sshUsername: null,
    sshPassword: null,
    sshKeyFingerprint: null,
    authMethod: "key",
    image: "codercom/code-server:latest",
    containerName: "vscode-3090",
    jupyterUrl: null,
    jupyterToken: null,
    accessUrls: null,
    duration: JSON.stringify({ hours: 12, minutes: 0 }),
    errorMessage: "Docker daemon unreachable on target host",
    startedAt: null,
    stoppedAt: null,
    expiresAt: null,
    scheduledTermination: null,
    createdAt: daysAgo(3),
  },
  {
    id: "ctr-006",
    userId: "mock-user-id",
    minerId: "miner-008",
    resourceId: "res-gpu-006",
    subscriptionId: null,
    templateId: "tpl-008",
    status: "pending",
    paymentStatus: "pending",
    host: null,
    port: null,
    sshUsername: null,
    sshPassword: null,
    sshKeyFingerprint: null,
    authMethod: "both",
    image: "nvidia/cuda:12.4.1-devel-ubuntu22.04",
    containerName: "cuda-dev-h100",
    jupyterUrl: null,
    jupyterToken: null,
    accessUrls: null,
    duration: JSON.stringify({ hours: 48, minutes: 0 }),
    errorMessage: null,
    startedAt: null,
    stoppedAt: null,
    expiresAt: null,
    scheduledTermination: null,
    createdAt: hoursAgo(0.5),
  },
];

// ─── SSH Keys ─────────────────────────────────────────────────

export const mockSshKeys: SshKey[] = [
  {
    id: "key-001",
    userId: "mock-user-id",
    name: "Work Laptop",
    publicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGit...abc123 user@work-laptop",
    fingerprint: "SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8",
    isDefault: true,
    lastUsedAt: hoursAgo(12),
    createdAt: daysAgo(60),
  },
  {
    id: "key-002",
    userId: "mock-user-id",
    name: "Personal Desktop",
    publicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC...def456 user@desktop",
    fingerprint: "SHA256:ROQFvPThGrW4RuWLoL9tq9I9zJ42fK4XywyRtbOz/EQ",
    isDefault: false,
    lastUsedAt: daysAgo(5),
    createdAt: daysAgo(45),
  },
  {
    id: "key-003",
    userId: "mock-user-id",
    name: "CI/CD Pipeline",
    publicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGit...ghi789 ci@pipeline",
    fingerprint: "SHA256:bWo7R4SqhGvFPWc5hE5WKWJ8lLv3Tb3TU5u8M3Nfe9U",
    isDefault: false,
    lastUsedAt: hoursAgo(2),
    createdAt: daysAgo(20),
  },
];

// ─── Admin User Info ──────────────────────────────────────────

export const mockAdminUsers: AdminUserInfo[] = [
  {
    id: "user-001",
    clerkId: "clerk_001",
    email: "ade@polariscloud.ai",
    name: "Ade Ogunleye",
    role: "admin",
    status: "active",
    country: "NG",
    instanceCount: 3,
    createdAt: daysAgo(200),
  },
  {
    id: "user-002",
    clerkId: "clerk_002",
    email: "wanjiku@devhub.ke",
    name: "Wanjiku Kamau",
    role: "user",
    status: "active",
    country: "KE",
    instanceCount: 2,
    createdAt: daysAgo(150),
  },
  {
    id: "user-003",
    clerkId: "clerk_003",
    email: "thabo@capeai.co.za",
    name: "Thabo Mokoena",
    role: "provider",
    status: "active",
    country: "ZA",
    instanceCount: 0,
    createdAt: daysAgo(180),
  },
  {
    id: "user-004",
    clerkId: "clerk_004",
    email: "amara@ghanaml.com",
    name: "Amara Mensah",
    role: "user",
    status: "active",
    country: "GH",
    instanceCount: 1,
    createdAt: daysAgo(90),
  },
  {
    id: "user-005",
    clerkId: "clerk_005",
    email: "fatima@lagosai.ng",
    name: "Fatima Adeyemi",
    role: "user",
    status: "active",
    country: "NG",
    instanceCount: 4,
    createdAt: daysAgo(120),
  },
  {
    id: "user-006",
    clerkId: "clerk_006",
    email: "jan@eucompute.nl",
    name: "Jan de Vries",
    role: "provider",
    status: "active",
    country: "NL",
    instanceCount: 0,
    createdAt: daysAgo(160),
  },
  {
    id: "user-007",
    clerkId: "clerk_007",
    email: "sarah@londonml.co.uk",
    name: "Sarah Thompson",
    role: "provider",
    status: "active",
    country: "GB",
    instanceCount: 0,
    createdAt: daysAgo(200),
  },
  {
    id: "user-008",
    clerkId: "clerk_008",
    email: "kwame@accratech.gh",
    name: "Kwame Asante",
    role: "user",
    status: "suspended",
    country: "GH",
    instanceCount: 0,
    createdAt: daysAgo(70),
  },
  {
    id: "user-009",
    clerkId: "clerk_009",
    email: "nala@nairobidata.ke",
    name: "Nala Odhiambo",
    role: "verifier",
    status: "active",
    country: "KE",
    instanceCount: 0,
    createdAt: daysAgo(140),
  },
  {
    id: "user-010",
    clerkId: "clerk_010",
    email: "chidi@lagosnet.ng",
    name: "Chidi Eze",
    role: "user",
    status: "active",
    country: "NG",
    instanceCount: 1,
    createdAt: daysAgo(30),
  },
];

// ─── Platform Stats ───────────────────────────────────────────

export const mockPlatformStats: PlatformStats = {
  totalUsers: 247,
  totalMiners: 10,
  totalResources: 12,
  activeResources: 10,
  totalContainers: 89,
  runningContainers: 23,
  pendingApprovals: 3,
  totalRevenue: 152_430.50,
  monthlyRevenue: 28_750.00,
};

// ─── Lookup Helpers ───────────────────────────────────────────

export function getResourceById(id: string): ComputeResource | undefined {
  return mockResources.find((r) => r.id === id);
}

export function getResourceWithDetails(id: string): ResourceWithDetails | undefined {
  const resource = mockResources.find((r) => r.id === id);
  if (!resource) return undefined;

  const heartbeat = mockHeartbeats.find((h) => h.resourceId === id) ?? null;
  const miner = mockMiners.find((m) => m.id === resource.minerId) ?? null;

  return { ...resource, heartbeat, miner };
}

export function getHeartbeatForResource(resourceId: string): Heartbeat | undefined {
  return mockHeartbeats.find((h) => h.resourceId === resourceId);
}

export function getMinerById(id: string): Miner | undefined {
  return mockMiners.find((m) => m.id === id);
}

export function getTemplateById(id: string): Template | undefined {
  return mockTemplates.find((t) => t.id === id);
}

export function getContainerById(id: string): Container | undefined {
  return mockContainers.find((c) => c.id === id);
}

export function getSshKeyById(id: string): SshKey | undefined {
  return mockSshKeys.find((k) => k.id === id);
}
